<?php

$comments = [
    [
        'id' => 1,
        'name' => 'Marco Bianchi',
        'text' => 'Soggiorno fantastico presso l\'Hotel Belvedere. Personale cordiale, camera spaziosa e pulita. Consigliatissimo!',
        'rating' => 5,
        'date' => '2024-04-20',
        'hotel_id' => 1,
    ],
    [
        'id' => 2,
        'name' => 'Chiara Esposito',
        'text' => 'Hotel Futuro non ha corrisposto alle aspettative. Struttura datata e servizio scadente. Da evitare.',
        'rating' => 2,
        'date' => '2024-03-15',
        'hotel_id' => 2,
    ],
    [
        'id' => 3,
        'name' => 'Alessandro Ferrari',
        'text' => 'Soggiorno piacevole presso l\'Hotel Rivamare. Posizione fantastica, proprio di fronte al mare. Personale gentile e disponibile.',
        'rating' => 4,
        'date' => '2024-04-10',
        'hotel_id' => 3,
    ],
    [
        'id' => 4,
        'name' => 'Laura Moretti',
        'text' => 'Hotel Bellavista è stato un sogno! Vista mozzafiato e servizio impeccabile. Torneremo sicuramente.',
        'rating' => 5,
        'date' => '2024-05-01',
        'hotel_id' => 4,
    ],
    [
        'id' => 5,
        'name' => 'Davide Russo',
        'text' => 'Hotel Milano è una buona scelta per chi vuole essere vicino al centro. Camere pulite e personale cortese.',
        'rating' => 4,
        'date' => '2024-04-25',
        'hotel_id' => 5,
    ],
    [
        'id' => 6,
        'name' => 'Elena Conti',
        'text' => 'Soggiorno eccellente presso l\'Hotel Splendido. Atmosfera rilassante e servizio di alta qualità. Lo consiglio vivamente.',
        'rating' => 5,
        'date' => '2024-04-05',
        'hotel_id' => 6,
    ],
    [
        'id' => 7,
        'name' => 'Fabio Martini',
        'text' => 'Hotel Vista Mare offre una vista spettacolare sul mare. Perfetto per una vacanza rilassante. Ci torneremo sicuramente!',
        'rating' => 4,
        'date' => '2024-04-18',
        'hotel_id' => 7,
    ],
    [
        'id' => 8,
        'name' => 'Silvia Costa',
        'text' => 'Hotel Panorama ha una vista mozzafiato sulla città. Servizio impeccabile e camere confortevoli. Ottimo rapporto qualità-prezzo.',
        'rating' => 5,
        'date' => '2024-04-30',
        'hotel_id' => 8,
    ],
    [
        'id' => 9,
        'name' => 'Giacomo Ferrari',
        'text' => 'Soggiorno piacevole presso l\'Hotel Sole. Posizione comoda e atmosfera accogliente. Buon rapporto qualità-prezzo.',
        'rating' => 4,
        'date' => '2024-04-22',
        'hotel_id' => 9,
    ],
    [
        'id' => 10,
        'name' => 'Martina De Luca',
        'text' => 'Hotel Luna è stato un\'esperienza fantastica! Personale gentile, camere spaziose e pulite. Torneremo sicuramente.',
        'rating' => 5,
        'date' => '2024-04-12',
        'hotel_id' => 10,
    ],
    [
        'id' => 11,
        'name' => 'Francesca Romano',
        'text' => 'Hotel Mare e Monti offre una vista mozzafiato sul mare e sulle montagne. Atmosfera rilassante e personale cordiale.',
        'rating' => 5,
        'date' => '2024-04-08',
        'hotel_id' => 11,
    ],
    [
        'id' => 12,
        'name' => 'Antonio Rossetti',
        'text' => 'Soggiorno piacevole presso l\'Hotel Le Palme. Struttura accogliente e personale disponibile. Ottimo rapporto qualità-prezzo.',
        'rating' => 4,
        'date' => '2024-04-19',
        'hotel_id' => 12,
    ],
    [
        'id' => 13,
        'name' => 'Elena Santoro',
        'text' => 'Hotel La Pineta è immerso nella natura, perfetto per una fuga dalla città. Atmosfera tranquilla e personale cordiale.',
        'rating' => 4,
        'date' => '2024-03-30',
        'hotel_id' => 13,
    ],
    [
        'id' => 14,
        'name' => 'Roberto Bianchi',
        'text' => 'Hotel I Tigli offre un\'esperienza autentica sotto gli alberi secolari. Atmosfera accogliente e personale disponibile.',
        'rating' => 5,
        'date' => '2024-04-14',
        'hotel_id' => 14,
    ],
    [
        'id' => 15,
        'name' => 'Anna Ferrara',
        'text' => 'Soggiorno romantico presso l\'Hotel Rosa. Atmosfera suggestiva e personale attento alle esigenze degli ospiti.',
        'rating' => 4,
        'date' => '2024-04-17',
        'hotel_id' => 15,
    ],
    [
        'id' => 16,
        'name' => 'Simone Rizzo',
        'text' => 'Hotel Mediterraneo offre una vera esperienza culinaria del Mediterraneo. Cibo delizioso e personale cortese.',
        'rating' => 4,
        'date' => '2024-04-23',
        'hotel_id' => 16,
    ],
    [
        'id' => 17,
        'name' => 'Luisa Martini',
        'text' => 'Hotel Gardenia è un\'oasi di pace nel verde. Atmosfera rilassante e personale disponibile.',
        'rating' => 4,
        'date' => '2024-04-26',
        'hotel_id' => 17,
    ],
    [
        'id' => 18,
        'name' => 'Riccardo Rossi',
        'text' => 'Soggiorno piacevole presso l\'Hotel Stella. Struttura accogliente e personale cortese.',
        'rating' => 3,
        'date' => '2024-04-29',
        'hotel_id' => 18,
    ],
    [
        'id' => 19,
        'name' => 'Sara Esposito',
        'text' => 'Hotel Lido è stato un\'oasi di relax sulla costa. Atmosfera accogliente e personale disponibile.',
        'rating' => 4,
        'date' => '2024-04-16',
        'hotel_id' => 19,
    ],
    [
        'id' => 20,
        'name' => 'Paolo Moretti',
        'text' => 'Hotel Panettone offre un soggiorno confortevole e un\'ottima colazione. Personale cortese e attento.',
        'rating' => 5,
        'date' => '2024-04-21',
        'hotel_id' => 20,
    ],
    [
        'id' => 21,
        'name' => 'Giulia Rossi',
        'text' => 'Hotel Belvedere è stata una piacevole sorpresa! Camere confortevoli e pulite, colazione abbondante. Lo consiglio!',
        'rating' => 4,
        'date' => '2024-05-03',
        'hotel_id' => 1,
    ],
    [
        'id' => 22,
        'name' => 'Mario Esposito',
        'text' => 'Hotel Futuro ha bisogno di miglioramenti. Struttura vecchia e poco curata. Il personale è stato però cortese.',
        'rating' => 3,
        'date' => '2024-04-26',
        'hotel_id' => 2,
    ],
    [
        'id' => 23,
        'name' => 'Francesca Bianchi',
        'text' => 'Soggiorno rilassante presso l\'Hotel Rivamare. Posizione ottima e personale gentile. Torneremo sicuramente!',
        'rating' => 5,
        'date' => '2024-04-14',
        'hotel_id' => 3,
    ],
    [
        'id' => 24,
        'name' => 'Luigi Ferrari',
        'text' => 'Hotel Bellavista è stato un sogno! Vista spettacolare e servizio impeccabile. Consigliatissimo!',
        'rating' => 5,
        'date' => '2024-05-02',
        'hotel_id' => 4,
    ],
    [
        'id' => 25,
        'name' => 'Elena Moretti',
        'text' => 'Hotel Milano è stata una piacevole scoperta. Camere pulite e personale cordiale. Buon rapporto qualità-prezzo.',
        'rating' => 4,
        'date' => '2024-04-28',
        'hotel_id' => 5,
    ],
    [
        'id' => 26,
        'name' => 'Paolo Santoro',
        'text' => 'Hotel Splendido offre un soggiorno lussuoso e confortevole. Atmosfera rilassante e personale attento.',
        'rating' => 5,
        'date' => '2024-04-16',
        'hotel_id' => 6,
    ],
    [
        'id' => 27,
        'name' => 'Giorgia Martini',
        'text' => 'Hotel Vista Mare è un\'oasi di pace con vista sul mare. Atmosfera rilassante e personale cordiale.',
        'rating' => 4,
        'date' => '2024-04-29',
        'hotel_id' => 7,
    ],
    [
        'id' => 28,
        'name' => 'Luca Rossetti',
        'text' => 'Hotel Panorama offre una vista mozzafiato sulla città. Struttura moderna e personale cortese.',
        'rating' => 5,
        'date' => '2024-04-20',
        'hotel_id' => 8,
    ],
    [
        'id' => 29,
        'name' => 'Valentina Ferrari',
        'text' => 'Soggiorno piacevole presso l\'Hotel Sole. Atmosfera accogliente e personale disponibile. Ottimo rapporto qualità-prezzo.',
        'rating' => 4,
        'date' => '2024-04-24',
        'hotel_id' => 9,
    ],
    [
        'id' => 30,
        'name' => 'Fabrizio Conti',
        'text' => 'Hotel Luna è stato un\'esperienza indimenticabile! Camere spaziose e pulite, personale cortese. Torneremo sicuramente.',
        'rating' => 5,
        'date' => '2024-04-18',
        'hotel_id' => 10,
    ],
    [
        'id' => 31,
        'name' => 'Giorgio Morelli',
        'text' => 'Hotel Mare e Monti offre una vista spettacolare e un ambiente rilassante. Personale cordiale e disponibile.',
        'rating' => 4,
        'date' => '2024-04-30',
        'hotel_id' => 11,
    ],
    [
        'id' => 32,
        'name' => 'Elisa Santoro',
        'text' => 'Soggiorno piacevole presso l\'Hotel Le Palme. Atmosfera accogliente e personale cortese. Buon rapporto qualità-prezzo.',
        'rating' => 4,
        'date' => '2024-05-01',
        'hotel_id' => 12,
    ],
    [
        'id' => 33,
        'name' => 'Daniele Lombardi',
        'text' => 'Hotel La Pineta è immerso nella natura, perfetto per una fuga dalla città. Personale cordiale e atmosfera tranquilla.',
        'rating' => 4,
        'date' => '2024-05-02',
        'hotel_id' => 13,
    ],
    [
        'id' => 34,
        'name' => 'Martina Ferrari',
        'text' => 'Hotel I Tigli è stato un\'oasi di pace sotto gli alberi secolari. Atmosfera accogliente e personale disponibile.',
        'rating' => 5,
        'date' => '2024-05-03',
        'hotel_id' => 14,
    ],
    [
        'id' => 35,
        'name' => 'Andrea Romano',
        'text' => 'Soggiorno romantico presso l\'Hotel Rosa. Atmosfera suggestiva e personale attento. Ottimo per una fuga di coppia.',
        'rating' => 5,
        'date' => '2024-05-04',
        'hotel_id' => 15,
    ],
    [
        'id' => 36,
        'name' => 'Giovanni Esposito',
        'text' => 'Hotel Mediterraneo offre un\'esperienza culinaria autentica del Mediterraneo. Cibo delizioso e atmosfera accogliente.',
        'rating' => 4,
        'date' => '2024-05-05',
        'hotel_id' => 16,
    ],
    [
        'id' => 37,
        'name' => 'Alice Rizzo',
        'text' => 'Hotel Gardenia è un\'oasi di pace nel verde. Atmosfera rilassante e personale cordiale. Consigliato per una pausa relax.',
        'rating' => 4,
        'date' => '2024-05-06',
        'hotel_id' => 17,
    ],
    [
        'id' => 38,
        'name' => 'Marco Bianco',
        'text' => 'Soggiorno piacevole presso l\'Hotel Stella. Struttura accogliente e personale disponibile. Buon rapporto qualità-prezzo.',
        'rating' => 3,
        'date' => '2024-05-07',
        'hotel_id' => 18,
    ],
    [
        'id' => 39,
        'name' => 'Elisa Ferrari',
        'text' => 'Hotel Lido è stata una piacevole scoperta sulla costa. Atmosfera accogliente e personale cordiale. Consigliato per una vacanza rilassante.',
        'rating' => 4,
        'date' => '2024-05-08',
        'hotel_id' => 19,
    ],
    [
        'id' => 40,
        'name' => 'Giacomo Bianchi',
        'text' => 'Hotel Panettone offre un\'esperienza confortevole e un\'ottima colazione. Personale cortese e disponibile. Consigliato!',
        'rating' => 5,
        'date' => '2024-05-09',
        'hotel_id' => 20,
    ],
    [
        'id' => 41,
        'name' => 'Laura Conti',
        'text' => 'Hotel Belvedere è stato un soggiorno meraviglioso! Vista mozzafiato e personale cortese. Torneremo sicuramente.',
        'rating' => 5,
        'date' => '2024-05-10',
        'hotel_id' => 1,
    ],
    [
        'id' => 42,
        'name' => 'Federico Martini',
        'text' => 'Hotel Futuro ha bisogno di miglioramenti. Struttura vecchia e servizio non all\'altezza delle aspettative.',
        'rating' => 2,
        'date' => '2024-05-11',
        'hotel_id' => 2,
    ],
    [
        'id' => 43,
        'name' => 'Silvia Esposito',
        'text' => 'Soggiorno rilassante presso l\'Hotel Rivamare. Atmosfera tranquilla e personale disponibile. Consigliato!',
        'rating' => 4,
        'date' => '2024-05-12',
        'hotel_id' => 3,
    ],
    [
        'id' => 44,
        'name' => 'Roberto Ferrari',
        'text' => 'Hotel Bellavista offre una vista mozzafiato e un servizio impeccabile. Esperienza indimenticabile!',
        'rating' => 5,
        'date' => '2024-05-13',
        'hotel_id' => 4,
    ],
    [
        'id' => 45,
        'name' => 'Valentina Romano',
        'text' => 'Hotel Milano è stata una piacevole scoperta! Camere confortevoli e personale cortese. Ottimo rapporto qualità-prezzo.',
        'rating' => 4,
        'date' => '2024-05-14',
        'hotel_id' => 5,
    ],
    [
        'id' => 46,
        'name' => 'Davide Bianchi',
        'text' => 'Hotel Splendido offre un soggiorno lussuoso e confortevole. Atmosfera rilassante e personale attento. Consigliato!',
        'rating' => 5,
        'date' => '2024-05-15',
        'hotel_id' => 6,
    ],
    [
        'id' => 47,
        'name' => 'Martina Rizzo',
        'text' => 'Hotel Vista Mare è un posto incantevole per una vacanza rilassante. Atmosfera tranquilla e personale cordiale.',
        'rating' => 4,
        'date' => '2024-05-16',
        'hotel_id' => 7,
    ],
    [
        'id' => 48,
        'name' => 'Marco Santoro',
        'text' => 'Hotel Panorama offre una vista spettacolare sulla città. Struttura moderna e personale cortese. Torneremo sicuramente.',
        'rating' => 5,
        'date' => '2024-05-17',
        'hotel_id' => 8,
    ],
    [
        'id' => 49,
        'name' => 'Anna Morelli',
        'text' => 'Soggiorno piacevole presso l\'Hotel Sole. Atmosfera accogliente e personale disponibile. Consigliato per una vacanza in città.',
        'rating' => 4,
        'date' => '2024-05-18',
        'hotel_id' => 9,
    ],
    [
        'id' => 50,
        'name' => 'Paolo Conti',
        'text' => 'Hotel Luna è stato un soggiorno indimenticabile! Camere spaziose e personale cortese. Ottima esperienza!',
        'rating' => 5,
        'date' => '2024-05-19',
        'hotel_id' => 10,
    ],
];

function getComments($comments)
{
    $results = array_filter($comments, function ($element) {
        return $element['hotel_id'] == $_GET['hotelId'];
    });
    if (count($results) > 0) {
        return $results;
    } else {
        //gestisci no commenti
    }
}
